---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by FenghuiLee.
--- DateTime: 2023/9/8 10:27
---

json              = require('json')
sql               = require('sql')
dsn               = require('lua.lib.dsn')
mysql             = require('lua.lib.mysql')

local canal       = require('canal')
local _action     = canal.rawAction()
local _schema     = canal.rawSchema()
local _table      = canal.rawTable()
local _row        = canal.rawRow()
local _old_row    = canal.rawOldRow()
local entity      = {
    action  = _action,
    schema  = _schema,
    table   = _table,
    row     = _row,
    old_row = _old_row,
}
local rows, error = sql.query(
    dsn.test,
    ('select * from `%s`.`%s` limit 1;'):format(
        entity['schema'],
        entity['table']
    )
)
print(json.encode(rows), json.encode(error))
