---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by FenghuiLee.
--- DateTime: 2023/9/10 7:34
---

local dsn = {
    test = {
        addr     = '127.0.0.1:3306',
        user     = 'user',
        password = 'password',
    },
}

return dsn